import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Game, { Guess } from '../../common/components/Game';
import { get } from '../../common/utils/fetch';
import { maxGuesses } from '../../common/utils/functions';
import { addBaseUrl } from '../../common/utils/ssr';
import styles from '../../styles/GameHome.module.scss';
import { Game as GameDb } from '@prisma/client';

const GameHome: NextPage<{ game: GameDb & { entries: Guess[] } }> = ({
  game,
}) => {
  return (
    <div className={styles['game-home-container']}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['game-home-main']}>
        <div className={styles['game-home-scoring']}>
          <Image
            src="/logo.png"
            width={400}
            height={200}
            objectFit="contain"
            alt="Wordle Battle Tournament"
          />
          <hr className={styles['game-home-score-break']} />
        </div>
        <div className={styles['game-home-playfield']}>
          <Game maxGuesses={maxGuesses} game={game} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const game = await get(
    addBaseUrl(`/api/game/${context.query.id}`, !!context.req),
  );

  return {
    props: { game },
  };
};

export default GameHome;
